-- MySQL Script generated by MySQL Workbench
-- Fri Apr 29 19:18:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema finaldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema finaldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `finaldb` DEFAULT CHARACTER SET utf8 ;
USE `finaldb` ;

-- -----------------------------------------------------
-- Table `finaldb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(200) NULL,
  `carnetUsuario` VARCHAR(10) NULL,
  `carreraUsuario` VARCHAR(150) NULL,
  `claveUsuario` VARCHAR(250) NULL,
  `fotoPerfil` VARCHAR(250) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `carnetUsuario_UNIQUE` (`carnetUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb`.`Nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`Nota` (
  `idNota` INT NOT NULL AUTO_INCREMENT,
  `contenidoNota` VARCHAR(250) NULL,
  `fechaNota` VARCHAR(80) NULL,
  `tituloNota` VARCHAR(100) NULL,
  PRIMARY KEY (`idNota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb`.`Nota_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`Nota_Usuario` (
  `idNotaUsuario` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL,
  `idNota` INT NULL,
  PRIMARY KEY (`idNotaUsuario`),
  INDEX `usuario_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `nota_idx` (`idNota` ASC) VISIBLE,
  CONSTRAINT `usuarioNota`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `finaldb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nota`
    FOREIGN KEY (`idNota`)
    REFERENCES `finaldb`.`Nota` (`idNota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `nombreEvento` VARCHAR(45) NULL,
  `descripcionEvento` VARCHAR(160) NULL,
  `fechaInicio` VARCHAR(60) NULL,
  `fechaFinal` VARCHAR(60) NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb`.`Evento_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`Evento_Usuario` (
  `idEventoUsuario` INT NOT NULL AUTO_INCREMENT,
  `idEvento` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEventoUsuario`),
  INDEX `evento_idx` (`idEvento` ASC) VISIBLE,
  INDEX `usuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `evento`
    FOREIGN KEY (`idEvento`)
    REFERENCES `finaldb`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuarioEvento`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `finaldb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb`.`Todo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`Todo` (
  `idTodo` INT NOT NULL AUTO_INCREMENT,
  `tituloTodo` VARCHAR(45) NULL,
  `contenidoTodo` VARCHAR(45) NULL,
  `completado` TINYINT NULL,
  PRIMARY KEY (`idTodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb`.`Todo_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`Todo_Usuario` (
  `idTodo_Usuario` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL,
  `idTodo` INT NULL,
  PRIMARY KEY (`idTodo_Usuario`),
  INDEX `todo_idx` (`idTodo` ASC) VISIBLE,
  INDEX `usuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `todo`
    FOREIGN KEY (`idTodo`)
    REFERENCES `finaldb`.`Todo` (`idTodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuarioTodo`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `finaldb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
